spring:
  datasource:
    url: ${DB_URL:jdbc:mariadb://localhost:3306/simpleforum}
    username: ${DB_USER:simpleforum}
    password: ${DB_PASSWORD:simpleforum}
    driver-class-name: ${DB_DRIVER:org.mariadb.jdbc.Driver}
  jpa:
    properties:
      hibernate:
        dialect: ${DB_DIALECT:org.hibernate.dialect.MariaDBDialect}
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      username: ${REDIS_USERNAME:}
      password: ${REDIS_PASSWORD:root}
      database: ${REDIS_DATABASE:0}

---

spring:
  config:
    activate:
      on-profile: mariadb
  datasource:
    url: ${DB_URL:jdbc:mariadb://localhost:3306/simpleforum}
    username: ${DB_USER:simpleforum}
    password: ${DB_PASSWORD:simpleforum}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect

---

spring:
  config:
    activate:
      on-profile: mysql
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/simpleforum}
    username: ${DB_USER:simpleforum}
    password: ${DB_PASSWORD:simpleforum}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect