spring:
  application:
    name: SimpleForum
  datasource:
    hikari:
      auto-commit: false
      connection-timeout: 3000
      validation-timeout: 3000
      max-lifetime: 60000
      maximum-pool-size: 20
      minimum-idle: 10
      idle-timeout: 30000
  jpa:
    open-in-view: false
logging:
  file:
    path: ./logs

---

spring:
  config:
    activate:
      on-profile: development
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        hbm2ddl:
          auto: update
logging:
  level:
    root: debug
  file:
    name: ./dev.log

---

spring:
  config:
    activate:
      on-profile: production
  jpa:
    hibernate:
      ddl-auto: none
server:
  error:
    include-stacktrace: never
logging:
  level:
    root: info
  file:
    name: ./prod.log