spring:
  application:
    name: SimpleForum
  datasource:
    hikari:
      auto-commit: false
      connection-timeout: 3000
      validation-timeout: 3000
      max-lifetime: 60000
      maximum-pool-size: 20
      minimum-idle: 10
      idle-timeout: 30000
  jpa:
    open-in-view: false
    properties:
      hibernate:
        hbm2ddl:
          auto: update
  data:
    redis:
      timeout: 10000
      jedis:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
  cache:
    redis:
      time-to-live: 3600000

---

spring:
  config:
    activate:
      on-profile: production
  jpa:
    hibernate:
      ddl-auto: none